### ISSUE TITLE
Fix names with spaces/other symbols in them

### ISSUE THREAD

**Issue by SnackMcOgrelord** [Nageld/worldbot#2]
As is already known, there are problems with names like the dark character "Alm / Arum" due to her having a slash in her name, and/or having spaces. Based on the code, you also cannot search !c Alm / Arum (which would be the found name in the database) because it splits every space, so Alm / Arum is the same as just writing Alm. To fix this, instead of checking if the input is equal to the name in the database, check if the database name contains the input at any point in the name. Examples of this here:
https://jsfiddle.net/x1c84aLt/ (excuse my laziness of displaying the data through printing rather than showing on html, and a lot of inefficient variable usage)

This uses either includes, match, indexOf or regex testing, to find part of names, I've put them in order from least to most efficient search.  If I'm not mistaken all this would take would be a change in line 59 of the commands.js file to fit one of the given solutions.
With the current setup, includes or indexOf would be the easiest to implement as match and test requires creating a regex object to execute.

**Comment by Nageld** [comment]
Same as #3 .
