### ISSUE TITLE
Searching japanese names

### ISSUE THREAD

**Issue by SnackMcOgrelord** [Nageld/worldbot#3]
Assuming #2 makes the cut, it is very easy to implement searching for the japanese name **and** the english name at once. Realistically we would just assume that if it is not the english name, then it might be the japanese name.

To do this (and also include the change from #2) we would include the following (assuming the usage of indexOf)

` const unit = global.CharacterData.find(char => char.ENName.toLowerCase().indexOf(chars.toLowerCase() != -1) || char.JPName.toLowerCase() == chars.toLowerCase());`

Seeing as there is only one japanese name, we can assume that the input will always be exactly what the name is. This would also (albeit hacky) solve the issue of people trying to find Alm/Arum, as japanese names can be used.

**Comment by Nageld** [comment]
Once #5 gets merged in this will no longer be an issue. If interested the api source can be found at https://github.com/Nageld/worldflipper-api
